version: '3.8'

services:
  db:
    image: postgres:16
    container_name: my_postgres
    ports:
      - "${PSQL_PORT}:${PSQL_PORT}"
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:
