version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "host=database port=5432 user=postgres password=postgres dbname=honors_inventory sslmode=disable"
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: honors_inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:

      - db-data:/var/lib/postgresql/data

      - type: bind
        source: ./db-init
        target: /docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - app-network

volumes:
  db-data:


networks:
  app-network:
    driver: bridge